- Projects/templates/Projects/home.html
- Users/templates/registration/login.html
More clear issues for users with different roles
> Updated when to show pr verification button

- Projects/static/Projects/js/profile.js
- Projects/templates/Projects/home.html
Added Important Notice section
> added importatnt Notice section on Home

- Projects/views.py
Adds email notification to users when their PRs are verified by mentors in Projects/views.py -> response_pr function. Also cleans up English grammar in views.py
This closes #48
> This attempts to close the issue: "notify user when their PR is verified #48"

- Projects/static/Projects/css/profile.css
- Projects/templates/Projects/base.html
- Projects/templates/Projects/profile.html
separate css from profile.html #19
> separate css from profile.html

- Projects/static/Projects/js/profile.js
- Projects/templates/Projects/home.html
- Projects/templates/Projects/profile.html
The input field to enter PR was creating problem on home page(solved)
Index on scrolling fixed
Delete PR button activated
> Frontend and backend

- .idea/contri_original.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- .idea/workspace.xml
- Projects/templates/Projects/navbar.html
- Projects/views.py
Change the name of MENTORS and PROJECTS accordingly in navbar.html
> #63 Filter to issues added

- Projects/static/Projects/css/login.css
- Projects/views.py
- Users/static/Users/js/login.js
- Users/templates/registration/login.html
- Users/views.py
Proposed changes
1. Separated js from login.html to login.js
2. Added password confirmation field
> Kks0101 separate js

- Projects/static/Projects/css/login.css
- Users/templates/registration/login.html
- Users/views.py
> password verification field added in signup page

- Projects/static/Projects/css/login.css
- Users/static/Users/js/login.js
- Users/templates/registration/login.html
- Users/views.py
fixes #18 
JS code at the bottom of login.html under "/Users/Templates/registration/login.html" is separated and is contained in login.js file in "Users/static/Users/js/" directory.
> Separated js from html code

- Projects/views.py
Changes proposed
1. Fixed infinite scroll paging
2. tried to make more issues better
> views modified

- Projects/models.py
- Projects/static/Projects/css/home.css
- Projects/templates/Projects/home.html
> Label added

- ContriHub/urls.py
- Projects/static/Projects/js/profile.js
- Projects/templates/Projects/contribution_user.html
- Projects/templates/Projects/leaderboard.html
- Projects/templates/Projects/profile.html
- Projects/templates/Projects/prs_pending.html
- Projects/views.py
Added user contributions link on leaderboard page
> Ashwini571 ash dev

- ContriHub/urls.py
- Projects/static/Projects/js/profile.js
- Projects/templates/Projects/contribution_user.html
- Projects/templates/Projects/leaderboard.html
- Projects/templates/Projects/profile.html
- Projects/templates/Projects/prs_pending.html
- Projects/templates/Projects/prs_vclosed.html
- Projects/views.py
Ignore the changes in Contribution_user.html and leaderboard.html(That was of last commit and is already in queue for verification)
> #17 Fetching of PRs using Ajax

- ContriHub/settings.py
- Projects/static/Projects/css/navbar.css
- Projects/templates/Projects/home.html
- Projects/templates/Projects/navbar.html
- Projects/views.py
For now filtering facility according to users is done in current dropdown implementation. Also for better experience dropdown is made scrollable
fixes #103
> Filtering issues according to users

- Projects/templates/Projects/home.html
- Projects/views.py
Changing label status without reloading the whole page. I must say this was a very nice task. 
fixes part 1 of #119
> Reloadin prevented while changing label of an issue.

- Projects/templates/Projects/home.html
Now one can delete issues on next pages also.
> #119 Bug in reloading after removing issue from home page removed

- ContriHub/settings.py
- ContriHub/urls.py
- Projects/static/Projects/css/home.css
- Projects/static/Projects/js/profile.js
- Projects/templates/Projects/contribution_user.html
- Projects/templates/Projects/home.html
- Projects/templates/Projects/navbar.html
- Projects/templates/Projects/prs_vclosed.html
- Projects/views.py
implemented snackbars implementation instead of alert
fixes #135
> No alerts on home page

- ContriHub/settings.py
- ContriHub/urls.py
- Projects/static/Projects/css/home.css
- Projects/static/Projects/js/profile.js
- Projects/templates/Projects/contribution_user.html
- Projects/templates/Projects/home.html
- Projects/templates/Projects/navbar.html
- Projects/templates/Projects/prs_vclosed.html
- Projects/views.py
Some changes made in views.py as told in #140.
> Changes made as told in previous PR

- ContriHub/settings.py
- Projects/static/Projects/js/home.js
- Projects/templates/Projects/home.html
- Projects/views.py
Using the same form for editing which was used for adding the issue. Sending an extra value just to confirm whether the request is for a new issue or edit issue. Autofilling form when clicked on the edit button.
fixes #137
> Added API to edit issues for mentors. 

- Projects/static/Projects/js/home.js
- Projects/templates/Projects/home.html
- Projects/templates/Projects/navbar.html
added relevant ids and also now auto filling level and points in the editing form
> suggested changes made for edit issues API

- Projects/static/Projects/css/profile.css
- Projects/static/Projects/js/home.js
- Projects/static/Projects/js/profile.js
- Projects/templates/Projects/home.html
- Projects/templates/Projects/navbar.html
- Projects/templates/Projects/profile.html
- Projects/templates/Projects/prs_pending.html
- Projects/templates/Projects/prs_vclosed.html
- Projects/views.py
2 alert boxes removed on the profile page 
1. on deleting a pr
2. on verifying/rejecting a pr
fixes #135
> removed alertboxes on profile page
